import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { ApiClientError } from "@/lib/api-client";

const mocks = vi.hoisted(() => ({ mutateAsync: vi.fn(), onClose: vi.fn(), onComplete: vi.fn() }));
vi.mock("@/hooks/use-documents", () => ({ useUploadAndProcessDocument: () => ({ mutateAsync: mocks.mutateAsync, isPending: false }) }));
import { UploadDocumentDialog } from "@/components/documents/upload-document-dialog";

describe("UploadDocumentDialog", () => {
  beforeEach(() => { mocks.mutateAsync.mockReset(); mocks.onClose.mockReset(); mocks.onComplete.mockReset(); });
  it("validates required title and file", async () => { const user = userEvent.setup(); render(<UploadDocumentDialog open onClose={mocks.onClose} onComplete={mocks.onComplete} />); await user.click(screen.getByRole("button", { name: "Upload document" })); expect(screen.getByRole("alert")).toHaveTextContent("title"); await user.type(screen.getByLabelText("Title"), "Guide"); await user.click(screen.getByRole("button", { name: "Upload document" })); expect(screen.getByRole("alert")).toHaveTextContent("Choose a document file"); });
  it("shows selected metadata and rejects an unsupported file", () => { render(<UploadDocumentDialog open onClose={mocks.onClose} onComplete={mocks.onComplete} />); fireEvent.change(screen.getByLabelText("File"), { target: { files: [new File(["x"], "guide.docx", { type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" })] } }); expect(screen.getByText("guide.docx")).toBeInTheDocument(); expect(screen.getByRole("alert")).toHaveTextContent("PDF, Markdown, or TXT"); });
  it("submits a valid upload and reports processing success", async () => { const user = userEvent.setup(); mocks.mutateAsync.mockResolvedValue({ document: { id: "doc-1" }, processingFailed: false }); render(<UploadDocumentDialog open onClose={mocks.onClose} onComplete={mocks.onComplete} />); await user.type(screen.getByLabelText("Title"), "Guide"); const file = new File(["hello"], "guide.txt", { type: "text/plain" }); await user.upload(screen.getByLabelText("File"), file); await user.click(screen.getByRole("button", { name: "Upload document" })); await waitFor(() => expect(mocks.mutateAsync).toHaveBeenCalledWith({ title: "Guide", file })); expect(mocks.onComplete).toHaveBeenCalledWith(false); });
  it("reports processing failure while preserving the uploaded result", async () => { const user = userEvent.setup(); mocks.mutateAsync.mockResolvedValue({ document: { id: "doc-1" }, processingFailed: true }); render(<UploadDocumentDialog open onClose={mocks.onClose} onComplete={mocks.onComplete} />); await user.type(screen.getByLabelText("Title"), "Guide"); await user.upload(screen.getByLabelText("File"), new File(["hello"], "guide.txt", { type: "text/plain" })); await user.click(screen.getByRole("button", { name: "Upload document" })); await waitFor(() => expect(mocks.onComplete).toHaveBeenCalledWith(true)); });
  it("shows a safe upload API failure", async () => { const user = userEvent.setup(); mocks.mutateAsync.mockRejectedValue(new ApiClientError("This document already exists.", 409)); render(<UploadDocumentDialog open onClose={mocks.onClose} onComplete={mocks.onComplete} />); await user.type(screen.getByLabelText("Title"), "Guide"); await user.upload(screen.getByLabelText("File"), new File(["hello"], "guide.txt", { type: "text/plain" })); await user.click(screen.getByRole("button", { name: "Upload document" })); expect(await screen.findByRole("alert")).toHaveTextContent("already exists"); });
});
