"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ApiClientError } from "@/lib/api-client";
import { formatFileSize } from "@/lib/document-validation";
import { useDeleteDocument, useDocument, useProcessDocument } from "@/hooks/use-documents";
import { ChunkPreview } from "@/components/documents/chunk-preview";
import { DeleteDocumentDialog, documentTypeLabels, DocumentStatusBadge } from "@/components/documents/document-ui";

export function DocumentDetail({ documentId }: { documentId: string }) {
  const router = useRouter(); const query = useDocument(documentId);
  const process = useProcessDocument(documentId, false); const reprocess = useProcessDocument(documentId, true); const remove = useDeleteDocument(documentId);
  const [deleteOpen, setDeleteOpen] = useState(false); const [actionError, setActionError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  if (query.isLoading) return <div className="document-state"><h2>Loading document...</h2></div>;
  if (query.isError) return <div className="document-state"><h2>{query.error instanceof ApiClientError && query.error.status === 404 ? "Document not found" : "Document could not load"}</h2><p>Check the document reference and try again.</p><button className="secondary-button" onClick={() => query.refetch()}>Retry</button></div>;
  const document = query.data!; const actionPending = process.isPending || reprocess.isPending || remove.isPending || document.status === "processing";
  const runProcessing = async (again: boolean) => { setActionError(null); setNotice(null); try { await (again ? reprocess : process).mutateAsync(); setNotice(again ? "Document reprocessed successfully." : "Document processed successfully."); } catch (caught) { setActionError(caught instanceof ApiClientError ? caught.message : "The document could not be processed."); } };
  const confirmDelete = async () => { setActionError(null); try { await remove.mutateAsync(); router.replace("/knowledge-base"); } catch { setActionError("The document could not be deleted. Check storage access and try again."); } };
  return <div className="document-detail"><Link className="back-link" href="/knowledge-base">← Back to knowledge base</Link><div className="detail-header"><div><p className="eyebrow">{document.original_filename}</p><h1 className="detail-title">{document.title}</h1><p className="detail-customer">{documentTypeLabels[document.file_type]} · {formatFileSize(document.file_size_bytes)}</p></div><DocumentStatusBadge status={document.status} /></div><div className="document-actions">{document.status === "pending" && <button className="primary-button" disabled={actionPending} onClick={() => runProcessing(false)}>{process.isPending ? "Processing..." : "Process document"}</button>}{(document.status === "completed" || document.status === "failed") && <button className="primary-button" disabled={actionPending} onClick={() => runProcessing(true)}>{reprocess.isPending ? "Reprocessing..." : "Reprocess document"}</button>}<button className="secondary-button" disabled={process.isPending || reprocess.isPending || remove.isPending} onClick={() => query.refetch()}>Refresh status</button><button className="danger-button" disabled={actionPending} onClick={() => { setActionError(null); setDeleteOpen(true); }}>Delete document</button></div>{notice && <div className="success-notice" role="status">{notice}</div>}{actionError && !deleteOpen && <p className="form-error" role="alert">{actionError}</p>}{document.status === "failed" && <div className="failure-notice" role="alert"><strong>Processing failed</strong><span>The file could not be processed. Review the source file and try reprocessing it.</span></div>}<section className="document-meta"><div><span>Original filename</span><strong>{document.original_filename}</strong></div><div><span>File type</span><strong>{documentTypeLabels[document.file_type]}</strong></div><div><span>File size</span><strong>{formatFileSize(document.file_size_bytes)}</strong></div><div><span>Status</span><DocumentStatusBadge status={document.status} /></div><div><span>Version</span><strong>{document.version}</strong></div><div><span>Chunk count</span><strong>{document.chunk_count}</strong></div><div><span>Uploaded</span><strong>{new Date(document.created_at).toLocaleString()}</strong></div><div><span>Processed</span><strong>{document.processed_at ? new Date(document.processed_at).toLocaleString() : "Not yet"}</strong></div></section><ChunkPreview documentId={documentId} /><DeleteDocumentDialog document={document} open={deleteOpen} busy={remove.isPending} error={deleteOpen ? actionError : null} onCancel={() => { setDeleteOpen(false); setActionError(null); }} onConfirm={confirmDelete} /></div>;
}
