"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useQuery, useQueryClient, useMutation } from "@tanstack/react-query";
import { useAuth } from "@/components/auth/auth-provider";
import { addTicketMessage, getTicket, updateTicket } from "@/lib/api-client";
import type { TicketPriority, TicketStatus } from "@/types/api";
import { categoryLabels, PriorityBadge, StatusBadge, priorityLabels, statusLabels } from "@/components/tickets/ticket-ui";

export function TicketDetail({ ticketId }: { ticketId: string }) {
  const { session } = useAuth(); const queryClient = useQueryClient(); const [message, setMessage] = useState(""); const [error, setError] = useState<string | null>(null);
  const query = useQuery({ queryKey: ["ticket", ticketId], queryFn: () => getTicket(session!.access_token, ticketId), enabled: Boolean(session) });
  const update = useMutation({ mutationFn: (data: { status?: TicketStatus; priority?: TicketPriority }) => updateTicket(session!.access_token, ticketId, data), onSuccess: (ticket) => queryClient.setQueryData(["ticket", ticketId], ticket) });
  const send = useMutation({ mutationFn: () => addTicketMessage(session!.access_token, ticketId, { sender_type: "agent", sender_name: "", content: message.trim() }), onSuccess: () => { setMessage(""); queryClient.invalidateQueries({ queryKey: ["ticket", ticketId] }); } });
  if (query.isLoading) return <div className="ticket-state"><h2>Loading ticket...</h2></div>;
  if (query.isError) return <div className="ticket-state"><h2>{(query.error as { status?: number }).status === 404 ? "Ticket not found" : "Ticket could not load"}</h2><p>Check the ticket reference and try again.</p><button className="secondary-button" onClick={() => query.refetch()}>Retry</button></div>;
  const ticket = query.data!; const messages = ticket.conversations.flatMap((conversation) => conversation.messages).sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime());
  async function submitMessage(event: FormEvent) { event.preventDefault(); setError(null); if (!message.trim()) { setError("Write a message before sending."); return; } try { await send.mutateAsync(); } catch { setError("The message could not be sent."); } }
  return <div className="ticket-detail"><Link className="back-link" href="/tickets">← Back to tickets</Link><div className="detail-header"><div><p className="eyebrow">{ticket.ticket_number}</p><h1 className="detail-title">{ticket.subject}</h1><p className="detail-customer">{ticket.customer_name} · {ticket.customer_email}</p></div><div className="detail-badges"><StatusBadge value={ticket.status} /><PriorityBadge value={ticket.priority} /></div></div><section className="detail-meta"><div><span>Plan</span><strong>{ticket.customer_plan}</strong></div><div><span>Category</span><strong>{categoryLabels[ticket.category]}</strong></div><div><span>Created</span><strong>{new Date(ticket.created_at).toLocaleDateString()}</strong></div><label><span>Status</span><select value={ticket.status} onChange={(event) => update.mutate({ status: event.target.value as TicketStatus })}>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label><span>Priority</span><select value={ticket.priority} onChange={(event) => update.mutate({ priority: event.target.value as TicketPriority })}>{Object.entries(priorityLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></section><section className="conversation-panel"><div className="section-heading"><div><p className="section-kicker">Conversation</p><h2>Customer history</h2></div><span>{messages.length} messages</span></div>{messages.length === 0 ? <div className="conversation-empty">No messages yet. Add the first response below.</div> : <div className="timeline">{messages.map((item) => <article className={`message message-${item.sender_type}`} key={item.id}><div className="message-top"><strong>{item.sender_name}</strong><time>{new Date(item.created_at).toLocaleString()}</time></div><p>{item.content}</p></article>)}</div>}<form className="message-composer" onSubmit={submitMessage}><textarea rows={4} placeholder="Write an internal support response..." value={message} onChange={(event) => setMessage(event.target.value)} aria-label="Message" />{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button" disabled={send.isPending}>{send.isPending ? "Sending..." : "Send message"}</button></form></section></div>;
}